# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: be29831
_src_path: https://github.com/schwallergroup/copier-liac.git
author_email: null
author_name: Anastasia
enforce_code_style: false
github_org: anastasiafloris
package_name: ppchemproject
project_name: ppchemproject
short_description: Project for pp
